blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Q&A Forum
    url: https://github.com/wareneutron/covid19-tracker-cli/discussions/new?category=q-a
    about: Have a question? Let us know!
  - name: ğŸ§  Suggestions
    url: https://github.com/wareneutron/covid19-tracker-cli/discussions/new?category=brainstorm
    about: Have an idea or suggestion? Let us know!
  - name: ğŸ“š Documentation
    url: https://docs.wareneutron.com/covid19-tracker-cli
    about: Official Documentation for COVID-19 Tracker & CLI
